common_deps(
    "//system:folly",
    "//system:glog",
    "//system:gtest",
    "//system:proxygenlib",
    "//system:wangle",
)

create_lib("Common", [name("//src", "EnumHash"), name("//src", "HTTPRequest"), name("//src", "StreamingHTTPHandler")], header_only=True)

create_test("ConfigTest", [name("//src", "Config"), name("Common")])
create_test("RouteTest", [name("//src", "Route"), name("Common")])
create_test("StaticRouteTest", [name("//src", "StaticRoute"), name("Common")])
create_test("HTTPHandlerTest", [name("//src", "HTTPHandler")])
create_test("HTTPHandlerFactoryTest", [name("//src", "HTTPHandlerFactory"), name("Common")])


create_test("HTTPRequestTest", [name("//src", "HTTPRequest")])
create_test("HTTPResponseTest", [name("//src", "HTTPResponse")])
create_test("RouterTest", [name("//src", "Router")])
create_test("PostParserTest", [name("//src", "PostParser"), name("Common")])
