common_deps(
    "//system:folly",
    "//system:glog",
    "//system:gtest",
    "//system:proxygenlib",
    "//system:wangle",
)

create_test("HTTPRequestTest", [name("//src", "HTTPRequest")])
create_test("HTTPResponseTest", [name("//src", "HTTPResponse")])
create_test("RouteTest", [name("//src", "Route")])
create_test("RouterTest", [name("//src", "Router")])
